### ISSUE TITLE
Add /kickstart endpoint for rendering ks files

### ISSUE THREAD

**Issue by adamschaub** [coreos/matchbox#224]
To make coreos-baremetal more relevant in heterogeneous environments. Adding a /kickstart endpoint will allow non-CoreOS machines to make the same use of group metadata that ignition/cloud endpoints do.

**Comment by brianredbeard** [comment]
This sounds completely reasonable.  Due to some of the intricacies of how Anaconda parses Kickstart files and the expectations around automatically handling LVM configuration, packages, etc I would say we should identify someone with this type of Anaconda expertise and have them collaborate.

**Comment by adamschaub** [comment]
@brianredbeard Point well taken. Any recommendations? I hear you're a Red Hat survivor.

**Comment by brianredbeard** [comment]
@adamschaub While we've tried to not paint anything into a corner on this, we're also making sure that it allows for a first class deployment experience for CoreOS hosts.  Before we can spend any time worrying about the experience for rpm based distros we need to get it right for ourselves.  This project was borne out of a number of deficiencies (for the deployment of CoreOS at least) in Cobbler, Spacewalk, Foreman, Razor, Juju, etc.  When folks from those communities belly up to the bar to collaborate we'll be happy to have them along for the ride, but we can't spare the cycles at the moment to work on non-core features at the expense of direct needs that I've had for a number of years.

**Comment by adamschaub** [comment]
@brianredbeard Couldn't agree more, I don't want to push to derail current priorities. We can provide the development cycles. To reaffirm, if we bring in external effort to contribute this feature, it could find a home in the project?

**Comment by dghubble** [comment]
The project structure should allow booting and provisioning other distributions, it just has CoreOS config file support at the moment. I'd like to see kickstart (or other) configs supported, but don't have the time to spend on it right now so contributions would be welcome.

One option might be to support a `/generic` config endpoint which just hooks into the group matching and profiles and templates any files provided without further logic. This means folks could try out serving kickstart files (or other configs), but without type or validation support until that's ready and can move to a dedicated, named endpoint. Its enough to try it out and see how it feels.

**Comment by adamschaub** [comment]
Sorry for the issue ref clutter. I realized late into the process that I needed to wrestle a few files around to make cleaner commits, and bad decisions ensued O.o

I've issued a PR implementing a `/generic` endpoint for the bootcfg HTTP server, as @dghubble had suggested. Let me know how you feel about the changes. Some feature like this could really help us fit coreos-baremetal into our architecture.

**Comment by dghubble** [comment]
The generic endpoint is available in the new `v0.4.0` release.

**Comment by rothgar** [comment]
Are the endpoints be pluggable? That way someone could drop a go template in a path and it could render the metadata however their template specified?

eg I could make a kickstart.template with all the necessary portions ( %pre, %post, etc.) and use metadata to render the config

**Comment by dghubble** [comment]
@rothgar yeah, the idea was for generic to be any Go template file (which could happen to be a valid kickstart.template) as a way of experimenting with new config types before adding full support.

**Comment by dghubble** [comment]
Seeking a quality Go packages for kickstart syntax checking / validation.

**Comment by trunet** [comment]
can you please also add the generic to matchbox/client? this will be needed for terraform-provider-matchbox integration on https://github.com/coreos/terraform-provider-matchbox/issues/16.

**Comment by dghubble** [comment]
Generic/experimental template support is the way to render arbitrary templates (including kickstart files) for now. I'll consider the initial request to support heterogeneous environments solved via this feature.

Desired config formats (such as kickstart) can graduate to having dedicated endpoints when there is a nice validation package in Go for us to use. I'm not aware of any for kickstart at this time, so `/generic` (i.e. unvalidated) is suitable enough.

@trunet Opened #562 to track extending generic/experimental template support to the gRPC API.
