### ISSUE TITLE
Document a cache proxy setup for images

### ISSUE THREAD

**Issue by dghubble** [coreos/matchbox#297]
Production users may outgrow bootcfg's assets folder feature, which is primarily for small labs and development image serving. A recommended approach is to use a cache proxy container which serves and caches requested images and can be allowed to egress the network in a controlled way.

Add a container image, docs, and usage guide to contrib.

rel. #286

**Comment by dghubble** [comment]
A work in progress from @kbrwn https://github.com/kbrwn/rkt-squid

**Comment by danehans** [comment]
I would like to use a squid proxy to host my bootcfg coreos images instead of the local assets dir. It looks like https://github.com/kbrwn/rkt-squid has been inactive for a bit. I am looking at https://github.com/sameersbn/docker-squid as another option.

I am trying to understand the workflow. Would I run the get-coreos script from my squid proxy to cache the kernel/initrd, verify sigs, etc.. and simply update the initrd/kernel values in my profiles to use the actual coreos urls:

**profile example:**
`{
  "id": "bootkube-controller",
  "name": "bootkube Ready Controller",
  "boot": {
    "kernel": "https://beta.release.core-os.net/amd64-usr/1185.1.0/coreos_production_pxe.vmlinuz",
    "initrd": ["https://beta.release.core-os.net/amd64-usr/1185.1.0/coreos_production_pxe.vmlinuz"],
...
    }
  },
  "cloud_id": "",
  "ignition_id": "bootkube-controller.yaml"
}`

cc @kbrwn

**Comment by dghubble** [comment]
I don't think you need to load the files with `get-coreos` if you're running it as an HTTP cache proxy. Anywhere those images are pulled will need to respect the proxy though.

**Comment by danehans** [comment]
@dghubble I'm trying to figure out how to pass the proxy setting to the server being managed by bootcfg. Do I simply add something like the following to the group metadata:

`  "metadata": {
    "HTTP_PROXY": "http://proxy.example.com:3128",
    ..
  }`

**Comment by dghubble** [comment]
Sure, then be sure to choose what to do with that metadata value during machine provisioning. Like setting the `http_proxy`, `https_proxy`, or `all_proxy` environment variables for apps. CoreUpdate, rkt, and Docker should respect it.

https://coreos.com/os/docs/latest/update-strategies.html#updating-behind-a-proxy
https://coreos.com/os/docs/latest/customizing-docker.html#use-an-http-proxy

In Ignition, you can either set those directly in systemd units via `Environment` or write those values to `/etc/environment` and use `EnvironmentFile` in your units.

**Comment by danehans** [comment]
I have this working using [docker-squid](https://github.com/sameersbn/docker-squid). I had to run squid in intercept mode (i.e. transparent proxy) in order for the [kernel](http://beta.release.core-os.net/amd64-usr/1185.1.0/coreos_production_pxe.vmlinuz) and [initrd](http://beta.release.core-os.net/amd64-usr/1185.1.0/coreos_production_pxe_image.cpio.gz) to get downloaded by ipxe. Lastly, I had to configure firewalld rules on the host running squid to allow redirection. Let me know if you would like me to submit a PR to add this info to the docs. If so, any guidance on where this info should live would be appreciated.

**Comment by danehans** [comment]
@dghubble I was thinking of extending this use-case, but I wanted to bounce it off you first to get your feedback. Here goes:

1. Server gets coreos installed by bootcfg over a secure provisioning network. Secure being no direct Internet access. Internet access goes through the squid transparent proxy.
2. During the first boot, the server is configured using Ignition... standard stuff.
3. As part of the Ignition config, the interface to the provisioning network is shutdown and configuration removed. Two different interfaces are configured, one for a public network and another for a private network. Networkd is restarted.

I'm essentially trying to use the secure provisioning network to bootstrap the managed servers,  disconnect the servers from the provisioning network and place them in their final home (public/private networks).

Is this type of setup something that you think is an expected security requirement or am I going way overboard?

**Comment by dghubble** [comment]
A good goal would be a small tutorial page under `Documentation` just showing the rkt and Docker commands to run the squid proxy as a transparent caching proxy and cluster environment variable settings. Probably similar to the usage section on [coreos/dnsmasq](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/network-setup.md#coreosdnsmasq)

@danehans If you just have some of that, no worries, feel free to put up a PR in some form and we can iterate.

**Comment by dghubble** [comment]
I've seen folks run `bootcfg` alongside ordinary network services or on isolated management networks which are only connected during a special provisioning window. It depends on the needs and environment and whether provisioning configs contain secrets or those come from another source. As an application, `bootcfg` isn't prescriptive.

In the last part of your description, it seems like having the machine shutdown its own access to the management network means an intruder could just enable it again. If a temporary provisioning window is wanted, I imagine a switch configuration/tags could do that better. Perhaps that's what you are saying, Ignition adds a systemd unit to notify to infrastructure that management access can be removed.

**Comment by danehans** [comment]
@dghubble I'll send a PR to add a squid section similar to dnsmasq.

**Comment by danehans** [comment]
@dghubble Thanks for your feedback regarding the use-case I described. Do you have a reference to:

> Ignition adds a systemd unit to notify to infrastructure that management access can be removed. 

I'm interested in better understanding how this is accomplished.

**Comment by danehans** [comment]
@dghubble I have this pretty well documented using Docker. I am having problems using rkt on cent7 following [this](https://coreos.com/rkt/docs/latest/distributions.html#centos) guide. Can I submit a PR that covers Docker and have someone with a rkt setup add a small section covering rkt? Here are the details:

```$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ rkt version
rkt Version: 1.14.0+git-dirty
appc Version: 0.8.7
Go Version: go1.6.3
Go OS/Arch: linux/amd64
Features: +TPM +SDJOURNAL

$ sudo rkt --net=host --volume cache,kind=host,source=/srv/docker/squid/cache,readOnly=true --mount volume=cache,target=/var/spool/squid3 --volume conf,kind=host,source=/home/localadmin/code/go/src/github.com/docker-squid/squid.conf,readOnly=true --mount volume=conf,target=/etc/squid3/squid.conf --insecure-options=image run docker://sameersbn/squid:3.3.8-20
image: using image from file /usr/libexec/rkt/stage1-host.aci
image: using image from local store for url docker://sameersbn/squid:3.3.8-20
run: disabling overlay support: "unsupported filesystem: missing d_type support"
Client died too early.
setexeccon("system_u:system_r:svirt_lxc_net_t:s0:c30,c194") failed: No such file or directory

**Comment by dghubble** [comment]
Sure, feel free. Most of us use rkt on my team so we can help add an example for both runtimes.

**Comment by ndouglas** [comment]
Are you still working on this, @danehans?  I was thinking about doing something along these lines.

**Comment by danehans** [comment]
@ndouglas please see https://github.com/coreos/matchbox/pull/455. It would be great for another person like yourself to validate the steps.
