### ISSUE TITLE
examples should not use .local tld

### ISSUE THREAD

**Issue by mischief** [coreos/matchbox#342]
.local is effectively reserved by RFC 6762 and could cause unintended side effects.

the examples in this repo should not use it.

**Comment by dghubble** [comment]
This is used across Kubernetes clusters in [coreos-kubernetes](https://github.com/coreos/coreos-kubernetes) and [bootkube](https://github.com/coreos/bootkube). Since this isn't causing a specific issue, I'll wait for the upstream decision / reason / story before decided whether to diverge.

**Comment by bzub** [comment]
I've had issues in the past with Go programs like etcd and flannel when they are statically linked (common, especially when run from small container images).  I was adding to the dnsmasq examples in this repo for my cluster with more .local addresses, and had a frustrating time figureing out that Go treats them differently.  Changing away from .local in my DNS settings everywhere resolved those issues.  I hope others aren't experiencing the same issues and walking away silently from good software.

Go's netgo DNS implementation tries not to resolve .local domains, and there is no other DNS method in statically linked Go programs.  
See: https://github.com/golang/go/blob/master/src/net/net.go#L57

This is probably a bug in Go's net package, but I still think the examples here should change.

**Comment by dghubble** [comment]
> I was adding to the dnsmasq examples in this repo for my cluster with more .local addresses

The tutorials and development examples in this project use `node*.example.com`. If you prefer

Setting the search domain is separate.

> --cluster_domain: Domain for this cluster. If set, kubelet will configure all containers to search this domain in addition to the host's search domains.

Seems rather mild. Perhaps the fact it is available misleads folks into thinking .local is a good choice for their apps/services, when some programs won't resolve it. @mischief we can collect a resolvable domain for the cluster in machine metadata and use it or leave it off entirely. Though, while upstream has it, folks may file an issue requesting it be kept/returned. Existing production clusters are fine.

**Comment by dghubble** [comment]
rel: https://github.com/coreos/coreos-kubernetes/issues/658

**Comment by dghubble** [comment]
I'd say this may be ingrained in Kubernetes deployments and folks would be affected if it were removed. Any opinions? @aaronlevy @pbx0 

If we don't plan to actually change this, I'd rather close this and the parent issue than leave them forever.

**Comment by aaronlevy** [comment]
I have no plans to change this. It is pretty much convention across kubernetes deployments (even in GKE). Adding this as a templated value doesn't provide much value - and it is additional pain during updates of many components (touches kube-dns, kubelets, tls certificates, probably more)

**Comment by dghubble** [comment]
Yup. Ok closing.
