### ISSUE TITLE
Rename coreos-baremetal to "matchbox"

### ISSUE THREAD

**Issue by dghubble** [coreos/matchbox#400]
As part of the rename of CoreOS Linux to Container Linux, coreos-baremetal is becoming CoreOS "matchbox". This transition will happen around the holidays and after, but done gradually since I recognize folks' attention is elsewhere during the season.

Meaning:

* bootcfg literally matches machines to provisioning profiles. It "matches boxes"
* matchbox is a nice tie in to CoreOS Ignition, the new provisioning system

What this means:

* github.com/coreos/coreos-baremetal will redirect to github.com/coreos/matchbox
* bootcfg binaries and tarballs will become "matchbox"
* bootcfg RPM dnf/yum repo will move to dghubble/matchbox
* Project docs and examples will be updated
* Tectonic enterprise documentation will be updated
* Update upstream Kubernetes documentation

This will also eliminate some confusion about coreos-baremetal vs. bootcfg (binary), about whether it is only suitable for Container Linux (its not), and about whether it can be used in the cloud (sure). The project will be easier to find via Googling as well.

**Comment by dghubble** [comment]
This rename is nearly complete. Still some rough edges until v0.5.0 is released and the new RPMs are posted. Thanks for the patience.

**Comment by urzds** [comment]
> bootcfg RPM dnf/yum repo will move to dghubble/matchbox

Shouldn't this be `coreos/matchbox`? Otherwise it looks like your private repository / having a repository with official looks appear in the manual seems more "professional".

**Comment by dghubble** [comment]
RPMs for Fedora 25/26 have been build, since the Go package is 1.7+ on those distributions.

@urzds Yep, we have a new Copr group so its `@CoreOS/matchbox`.
