### ISSUE TITLE
etcd-install

### ISSUE THREAD

**Issue by khanattlab** [coreos/matchbox#423]
I can get etcd and install-reboot to work. How can I get multiple nodes to install and configure etcd using etcd-install. Do I just add node json files in the examples/groups/etcd-install directory or do I need to make other changes? thanks

**Comment by dghubble** [comment]
I'm guessing you're following the tutorial for trying matchbox locally in QEMU/KVM? You can use any of the  [examples](https://github.com/coreos/matchbox/tree/master/examples) without adding new files, have `matchbox` mount the right data.

Fill in `ANY_EXAMPLE_DIR` with `etcd-install` or any of the other examples:

```
sudo rkt run --net=metal0:IP=172.18.0.2 --mount volume=data,target=/var/lib/matchbox --volume data,kind=host,source=$PWD/examples --mount volume=groups,target=/var/lib/matchbox/groups --volume groups,kind=host,source=$PWD/examples/groups/ANY_EXAMPLE_DIR quay.io/coreos/matchbox:latest -- -address=0.0.0.0:8080 -log-level=debug
```

```
sudo docker run -p 8080:8080 --rm -v $PWD/examples:/var/lib/matchbox:Z -v $PWD/examples/groups/ANY_EXAMPLE_DIR:/var/lib/matchbox/groups:Z quay.io/coreos/matchbox:latest -address=0.0.0.0:8080 -log-level=debug
```

If you're asking about the general strategy for how this works, take a look at [machine-lifecycle](https://github.com/coreos/matchbox/blob/master/Documentation/machine-lifecycle.md). Machines boot from disk first, unless a PXE boot is explicitly requested (via IPMI, etc.). On PXE boot, an Ignition file (such as install-reboot) is served to each machine. Its a small Ignition config only used to install to disk and download another Ignition file. On first boot from disk, Ignition runs during initramfs to provision the machine. In the case of the `etcd-install` examples, 3 machines are setup as a 3-node etcd cluster installed to disk.

**Comment by khanattlab** [comment]
I use IPXE and run the docker script to serve boot.ipxe to a bare-metal cluster. These are local right now  but I am trying to simulate creating bigger clusters in the lab. I used ignition to create the cluster with the etcd profile. I would like the same but installed to disk so we can turn on ipxe only during addition of a new node. I changed mac on the etcd-install node json files but it didnt work. Will double check and also look at the script. thanks

**Comment by dghubble** [comment]
Ok, the `devnet` script assumes you'll use rkt instead of docker, mainly bc its what my team is using during development. Skip that then.

Why are you changing MAC addresses? In the development setup, the `libvirt` script will always create 4 VMs with known MAC addresses. The examples are written to match against those MAC addresses. Its to simulate a real bare-metal network where machines are matched by some hardware identifier.

Initial PXE boot matches: https://github.com/coreos/matchbox/blob/master/examples/groups/etcd-install/install.json (no selectors)
Per-machine matches: https://github.com/coreos/matchbox/blob/master/examples/groups/etcd-install/node1.json#L5 (selector for mac address and os=installed)

**Comment by khanattlab** [comment]
I am using a real bare-metal network in the lab with Dell servers using NIC mac address as hardware identifier.

**Comment by dghubble** [comment]
Oh misread the line about them being local, but they bare-metal nodes on your local network, got it.

So if you've gone through [installation](https://github.com/coreos/matchbox/blob/master/Documentation/deployment.md), you should be able to copy the examples into `/var/lib/bootcfg` (or `/var/lib/matchbox`) and be sure the contents of `examples/groups/etcd-install` are in `/var/lib/bootcfg/groups`.

You'll want to use your own MAC addresses, add your SSH [public key](https://github.com/coreos/matchbox/tree/master/examples#ssh-keys) and remove `coreos.autologin` from the profile.

If you want a verbatim example, here are the files I use on in my lab. I don't have a stand-alone etcd install, but I do have k8s-install which should be similar. https://github.com/dghubble/metal

**Comment by khanattlab** [comment]
The verbatim example will be real helpful - thanks.

**Comment by dghubble** [comment]
Closing, bc I filed an issue to create a tutorial on this. Feel free to open new issues if you run into problems or if this doesn't go as planned
