### ISSUE TITLE
PXE boot continually matching 'install-reboot' profile

### ISSUE THREAD

**Issue by holygits** [coreos/matchbox#429]
Using k8s-install groups to PXE boot a libvirt VM. CoreOS installs fine but after a reboot it matches the 'install-reboot' profile again, rather than the k8s-(controller/worker) profile.

Matchbox logs show:
```
time="2017-01-31T21:10:12Z" level=info msg="HTTP GET /ignition?uuid=00000000-0000-0000-0000-000000000000&mac=52-54-00-b2-2f-86" 
time="2017-01-31T21:10:12Z" level=debug msg="Matched an Ignition or Fuze template" group=coreos-install labels=map[mac:52:54:00:b2:2f:86 uuid:00000000-0000-0000-0000-000000000000] profile=install-reboot 
time="2017-01-31T21:10:31Z" level=info msg="HTTP GET /ignition?uuid=00000000-0000-0000-0000-000000000000&mac=52-54-00-b2-2f-86&os=installed" 
time="2017-01-31T21:10:31Z" level=debug msg="Matched an Ignition or Fuze template" group=coreos-install labels=map[uuid:00000000-0000-0000-0000-000000000000 mac:52:54:00:b2:2f:86 os:installed] profile=install-reboot 
time="2017-01-31T21:10:31Z" level=info msg="HTTP HEAD /assets/coreos/1298.1.0/coreos_production_image.bin.bz2" 
time="2017-01-31T21:10:31Z" level=info msg="HTTP HEAD /assets/coreos/1298.1.0/coreos_production_image.bin.bz2.sig" 
time="2017-01-31T21:10:32Z" level=info msg="HTTP GET /assets/coreos/1298.1.0/coreos_production_image.bin.bz2.sig" 
time="2017-01-31T21:10:32Z" level=info msg="HTTP GET /assets/coreos/1298.1.0/coreos_production_image.bin.bz2" 
**time="2017-01-31T21:12:33Z" level=info msg="HTTP GET /ignition?uuid=00000000-0000-0000-0000-000000000000&mac=52-54-00-b2-2f-86&os=installed&os=installed" 
time="2017-01-31T21:12:33Z" level=debug msg="Matched an Ignition or Fuze template" group=coreos-install labels=map[uuid:00000000-0000-0000-0000-000000000000 mac:52:54:00:b2:2f:86 os:installed] profile=install-reboot** 

```

**Comment by dghubble** [comment]
Are you using the `scripts/libvirt` wrapper script? The `virt-install` invocation https://github.com/coreos/matchbox/blob/master/scripts/libvirt#L55 uses `--boot=hd,network` so you should see a GRUB screen after a reboot if there is a disk install. Its supposed to be as similar as possible to a real machine configured with a boot order disk, then network. If the VM attempts to PXE boot again, yes, it would be matched to the same Ignition. But the VM shouldn't PXE boot again. Is the machine rebooting itself (it should) or are you doing the shutdown/poweron? Somewhat recently we added `-events on_poweroff=preserve` to the virt-install invocation as well, so that if the host reboots itself, the VM is actually rebooted - this doesn't typically work that way in a `virt-install`.

For anyone stumbling across this question from Google, note that this concerns the QEMU/KVM local examples under libvirt. On real hardware, set the boot order to prefer disk first, then PXE/network.

**Comment by dghubble** [comment]
Are you sure you're running the correct example cluster? From those logs, it appears matchbox is giving the install-reboot profile even when os=installed is a query parameter. That makes me think you're using `k8s` instead of `k8s-install`.

You want to be doing something like:

    sudo ./scripts/devnet create k8s-install
    sudo ./scripts libvirt create

to simulate a bare-metal cluster PXE booting, installing to disk, rebooting, and provisioning as a Kubernetes cluster. The `k8s` example is for PXE booting straight to a Kubernetes cluster (faster, less realistic for most people).

**Comment by holygits** [comment]
I'm not using `scripts/libvrit` directly but I've taken the `virt-install` command from the libvirt script to manually create a VM on a host of my choosing.
i.e. `sudo virt-install --name node2 $COMMON_VIRT_OPTS --network=bridge=br0,model=e1000,mac=52:54:00:b2:2f:86 --boot=hd,network -d`
I manually created a bridge interface `br0` to bind the the physical hosts eth0, this is working correctly.

Matchbox is running on a separate host to the target libvirt VM.

My boot order is set correctly, I can verify that the VM reboots to disk as I am able to SSH into the box.

I have also tried using `qemu-system` directly, producing the same results.
```qemu-system-x86_64 -smp cores=8 -m 4096 -device e1000,netdev=net0,mac=52:54:00:b2:2f:86 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -drive file=node2.qcow2,format=qcow2,media=disk -enable-kvm -boot cn --curses```

**Comment by dghubble** [comment]
Just curl http://<matchbox.foo>:8080/ignition?mac=52:54:00:b2:2f:86` and `http://<matchbox.foo>:8080/ignition?mac=52:54:00:b2:2f:86&os=installed`. You should get the install reboot Ignition from the first one and the Kubernetes controller/worker Ignition from the second.

If they return the same output, check your `/var/lib/matchbox/groups` to be sure you have a group for matching both the machine duing PXE boot and another for matching the machine post-install. Or use a default group like the examples. If you're writing those files by hand, be sure they are valid JSON.

Once matchbox serves the correct responses, matchbox is functioning correctly. As far as usage, the provided working examples are what you should consult for adjusting your setup.

**Comment by holygits** [comment]
Contents of `/var/lib/matchbox/groups/` in my matchbox container
```
# install.json
{
  "id": "coreos-install",
  "name": "CoreOS Install",
  "profile": "install-reboot",
  "metadata": {
    "coreos_channel": "alpha",
    "coreos_version": "1298.1.0",
    "ignition_endpoint": "http://bootcfg.example.com:8080/ignition",
    "baseurl": "http://bootcfg.example.com:8080/assets/coreos",
    "ssh_authorized_keys": [
      "ssh-rsa XXX"
    ]
  }
}
# node1.json
{
  "id": "node1",
  "name": "k8s controller",
  "profile": "k8s-controller",
  "selector": {
    "os": "installed",
    "mac": "52:54:00:a1:9c:ae"
  },
  "metadata": {
    "container_runtime": "docker",
    "domain_name": "node1.example.com",
    "etcd_initial_cluster": "node1=http://node1.example.com:2380",
    "etcd_name": "node1",
    "k8s_cert_endpoint": "http://bootcfg.example.com:8080/assets",
    "k8s_dns_service_ip": "10.3.0.10",
    "k8s_etcd_endpoints": "http://node1.example.com:2379",
    "k8s_pod_network": "10.2.0.0/16",
    "k8s_service_ip_range": "10.3.0.0/24",
    "ssh_authorized_keys": [
      "ssh-rsa XXX"
    ]
  }
}
# node2.json
{
  "id": "node2",
  "name": "k8s worker",
  "profile": "k8s-worker",
  "selector": {
    "os": "installed",
    "mac": "52:54:00:b2:2f:86",
  },
  "metadata": {
    "container_runtime": "docker",
    "domain_name": "node2.example.com",
    "etcd_initial_cluster": "node1=http://node1.example.com:2380",
    "k8s_cert_endpoint": "http://bootcfg.example.com:8080/assets",
    "k8s_controller_endpoint": "https://node1.example.com",
    "k8s_dns_service_ip": "10.3.0.10",
    "k8s_etcd_endpoints": "http://node1.example.com:2379",
    "ssh_authorized_keys": [
      "ssh-rsa XXX"
    ]
  }
}
# node3.json
{
  "id": "node3",
  "name": "k8s worker",
  "profile": "k8s-worker",
  "selector": {
    "os": "installed",
    "mac": "52:54:00:c3:61:77",
  },
  "metadata": {
    "container_runtime": "docker",
    "domain_name": "node3.example.com",
    "etcd_initial_cluster": "node1=http://node1.example.com:2380",
    "k8s_cert_endpoint": "http://bootcfg.example.com:8080/assets",
    "k8s_controller_endpoint": "https://node1.example.com",
    "k8s_dns_service_ip": "10.3.0.10",
    "k8s_etcd_endpoints": "http://node1.example.com:2379",
    "ssh_authorized_keys": [
      "ssh-rsa XXX"
    ]
  }
}
```

After booting to HDD and SSHing to the VM I can see these errors:
```
[  293.441761] EXT4-fs error (device sda9): ext4_xattr_block_get:319: inode #4886: comm systemd-timesyn: bad block 16669
[  293.447429] Aborting journal on device sda9-8.
[  293.450565] EXT4-fs (sda9): Remounting filesystem read-only
[  293.452689] SELinux: inode_doinit_with_dentry:  getxattr returned 117 for dev=sda9 ino=4886
[  293.455925] EXT4-fs error (device sda9): ext4_xattr_block_get:319: inode #4886: comm systemd-timesyn: bad block 16669

```

**Comment by dghubble** [comment]
Hm, well if you are booting from disk (Ignition installed CoreOS) and able to SSH (Ignition added your ssh authorized keys among other things during provisioning)  this now seems related to the disk or the `coreos-install` [script](https://coreos.com/os/docs/latest/installing-to-disk.html) which writes those partitions initially. Is this reproducible?

**Comment by holygits** [comment]
Doh. my node2.json was invalid, had a stray comma.
`  "selector": {
    "os": "installed",
    "mac": "52:54:00:b2:2f:86",
  },
`
@dghubble thanks for all your help!
Logs looking good now.
```
time="2017-01-31T22:51:13Z" level=info msg="Starting matchbox HTTP server on 0.0.0.0:8080" 
time="2017-01-31T22:51:32Z" level=info msg="HTTP GET /boot.ipxe.0" 
time="2017-01-31T22:51:32Z" level=info msg="HTTP GET /ipxe?uuid=00000000-0000-0000-0000-000000000000&mac=52-54-00-b2-2f-86&domain=stratos.dotlovesdata&hostname=node2&serial=" 
time="2017-01-31T22:51:32Z" level=debug msg="Matched an iPXE config" labels=map[uuid:00000000-0000-0000-0000-000000000000 mac:52:54:00:b2:2f:86 domain:stratos.dotlovesdata hostname:node2 serial:] profile=install-reboot 
time="2017-01-31T22:51:32Z" level=info msg="HTTP GET /assets/coreos/1298.1.0/coreos_production_pxe.vmlinuz" 
time="2017-01-31T22:51:35Z" level=info msg="HTTP GET /assets/coreos/1298.1.0/coreos_production_pxe_image.cpio.gz" 
time="2017-01-31T22:51:55Z" level=info msg="HTTP GET /boot.ipxe.0..." 
time="2017-01-31T22:52:06Z" level=info msg="HTTP GET /ignition?uuid=00000000-0000-0000-0000-000000000000&mac=52-54-00-b2-2f-86" 
time="2017-01-31T22:52:06Z" level=debug msg="Matched an Ignition or Fuze template" group=coreos-install labels=map[uuid:00000000-0000-0000-0000-000000000000 mac:52:54:00:b2:2f:86] profile=install-reboot 
time="2017-01-31T22:52:23Z" level=info msg="HTTP GET /ignition?uuid=00000000-0000-0000-0000-000000000000&mac=52-54-00-b2-2f-86&os=installed" 
time="2017-01-31T22:52:23Z" level=debug msg="Matched an Ignition or Fuze template" group=node2 labels=map[mac:52:54:00:b2:2f:86 os:installed uuid:00000000-0000-0000-0000-000000000000] profile=k8s-worker 
time="2017-01-31T22:52:23Z" level=info msg="HTTP HEAD /assets/coreos/1298.1.0/coreos_production_image.bin.bz2" 
time="2017-01-31T22:52:23Z" level=info msg="HTTP HEAD /assets/coreos/1298.1.0/coreos_production_image.bin.bz2.sig" 
time="2017-01-31T22:52:24Z" level=info msg="HTTP GET /assets/coreos/1298.1.0/coreos_production_image.bin.bz2.sig" 
time="2017-01-31T22:52:24Z" level=info msg="HTTP GET /assets/coreos/1298.1.0/coreos_production_image.bin.bz2" 
time="2017-01-31T22:54:27Z" level=info msg="HTTP GET /assets/tls/ca.pem" 
time="2017-01-31T22:54:27Z" level=info msg="HTTP GET /assets/tls/worker-key.pem" 
time="2017-01-31T22:54:27Z" level=info msg="HTTP GET /assets/tls/worker.pem" 
```

**Comment by dghubble** [comment]
Ah. Yeah, that's tracked in https://github.com/coreos/matchbox/issues/302

**Comment by khanattlab** [comment]
Trying the same except its just etcd nodes instead of Kubernetes.  Somehow the install is not picking the node jsons but I am guessing I must have messed up some editing also.  thanks
