### ISSUE TITLE
Kubelet daemonset not deployed?

### ISSUE THREAD

**Issue by fmoctezuma** [coreos/matchbox#448]
Hi , 
I'm playing around upgrading a self-hosted Kubernetes cluster, deployed with Matchbox.
I already upgrade the kube-apiserver, kube-controller-manager and kube-proxy to a new version,
but I can't do it with kubelet,  I couldn't find it as a daemonset or deployment.
Is there already another way to do it that maybe am I missing ?
I'm following the official [docs ](https://github.com/coreos/matchbox/blob/master/Documentation/bootkube-upgrades.md)

```
root@selfhosted-k8s-lab:~/matchbox# kubectl get daemonsets -n kube-system
NAME                   DESIRED   CURRENT   READY     NODE-SELECTOR   AGE
checkpoint-installer   2         2         2         master=true     1h
kube-apiserver         2         2         2         master=true     1h
kube-flannel           3         3         3         <none>          1h
kube-proxy             3         3         3         <none>          1h
```

```
root@selfhosted-k8s-lab:~/matchbox# kubectl get deployments -n kube-system
NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-controller-manager   2         2         2            2           2h
kube-dns                  1         1         1            1           2h
kube-scheduler            2         2         2            2           2h
```

During daemonset creation, ..

```
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  538.972665] bootkube[5]: I0302 20:03:35.679619       5 log.go:19] daemonset "kube-apiserver" created
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  538.973415] bootkube[5]:         created          kube-apiserver daemonset
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  539.162182] bootkube[5]: I0302 20:03:35.869168       5 log.go:19] daemonset "kube-flannel" created
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  539.162725] bootkube[5]:         created            kube-flannel daemonset
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  539.184866] bootkube[5]: I0302 20:03:35.891783       5 log.go:19] daemonset "kube-proxy" created
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  539.185538] bootkube[5]:         created              kube-proxy daemonset
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  539.241075] bootkube[5]: I0302 20:03:35.948083       5 log.go:19] daemonset "checkpoint-installer" created
Mar 02 20:03:35 node1.example.com bootkube-start[1375]: [  539.241647] bootkube[5]:         created    checkpoint-installer daemonset
```

**Comment by dghubble** [comment]
Self-hosted Kubernetes clusters support running the kubelet on the host or as a daemonset (with a fallback on-host kubelet).

The docs [here](https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md) use the on-host Kubelet. There are some known issues with using the daemonset kubelet (rel. kubectl proxy commands) so we currently recommend the on-host kubelet until issues are fixed.

That means, you won't find a kubelet daemonset until that flag is added back again. To upgrade the kubelet, you'll need to connect to each node, edit the kubelet systemd unit to use the next version (there is an Environment File), and restart each one. Its a manual process which is why we've invested in getting each part of the control plane self-hosted over time.

**Comment by dghubble** [comment]
A note in the upgrade document would be useful, you're right that the doc is out of sync with the present.

**Comment by yazpik** [comment]
Make sense thanks @dghubble,
So I'm having a look at the kubelet-wrapper _/etc/systemd/system/kubelet.service_ and the environment file points to 
```
EnvironmentFile=/etc/kubernetes/kubelet.env
```
Just changed the hyperkube version there to a new one, I also did a rkt stop of the current hyperkube container, and couple of minutes later the rkt container was running again with the new hyperkube version and worked fine in two of the nodes. 
Not sure if this is what you meant with the "restart of each one", 
I'm going to replicate the same on the rest of the nodes.

One thing I'm seeing is the kube-flannel and kube-proxy are stuck on "Terminating" status,  

- I was using my corporate user account when I created the issue, ignore that.

**Comment by dghubble** [comment]
The systemd unit happens to ExecStart a rkt run process, but that's just a detail. You can restart it like any other system service actually.

    systemctl restart kubelet

**Comment by dghubble** [comment]
By flannel and proxy being "stuck", how long are we talking here?

**Comment by yazpik** [comment]
Allright, Just tested going from 1.5.2 to 1.5.3 it worked pretty well updating all the components and manually updating the kubelet on each node, while running 50 pods, updating the images and so on.
Errors related with flannel and proxy being stuck I think are related with the fact I was trying something crazy like 1.5.2 to 1.6.0-beta.
Thanks

**Comment by dghubble** [comment]
Nice. Yeah, bootkube is still testing the 1.6 beta and migration so mileage may vary.
