### ISSUE TITLE
Bootkube Terraform Missing Step

### ISSUE THREAD

**Issue by danehans** [coreos/matchbox#502]
I had to use the `terraform get` command for `terraform plan` to work:
```
$ terraform plan
Failed to load root config module: Error loading modules: module profiles: not found, may need to be downloaded using 'terraform get'
```
I then run `terraform get`:
```
$ terraform get
Get: file:///home/localadmin/code/go/src/github.com/coreos/matchbox/examples/terraform/modules/profiles
```
and rerun `terraform plan`:
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
<SNIP>
```

Let me know if you would like me to submit a PR to update the readme.

**Comment by dghubble** [comment]
Yep, that's needed. A PR would be welcome, thanks

**Comment by dghubble** [comment]
We might also try to mention how one would import these modules in their own repo of terraform configs.

```
// Create popular machine Profiles (convenience module)
module "profiles" {
  source                 = "git::https://github.com/coreos/matchbox.git//examples/terraform/modules/profiles?ref=64168bc42edd5f249b5f6c542319c202a308434b"
  matchbox_http_endpoint = "${var.matchbox_http_endpoint}"
  coreos_version         = "${var.container_linux_version}"
}
```

**Comment by danehans** [comment]
Interesting... let me look into that.

**Comment by danehans** [comment]
I am new to the bootkube-install, so I'm trying to better understand the workflow. I understand the coreos-install stage of the workflow, but things get fuzzy during the 2nd stage. After the coreos-install script completes, the machine reboots. However, I don't understand how the os=installed label gets set on the machine and presented to matchbox.

It appears that /usr/share/oem/coreos-install.json is created and populated with the stage 2 container linux config (i.e. bootkube-controller). I do not understand how this file is created and populaed. I thought it was created by the coreos-install script, but the [dir structure](https://github.com/coreos/init/blob/master/bin/coreos-install#L476) differs.

**Comment by dghubble** [comment]
In the `coreos-install` profile's Container Linux config it requests the config from matchbox with `os=installed` [appended](https://github.com/coreos/matchbox/blob/master/examples/terraform/modules/profiles/cl/coreos-install.yaml.tmpl#L23). The coreos-install script included on Container Linux by default, takes arguments like `-i` or `-c` to set an Ignition or Cloud-Config to use after the install.

Its an implementation detail of the example profile which you could do in different ways if you wanted.
