### ISSUE TITLE
scripts: Confusing/conflicting paths for cert-gen script

### ISSUE THREAD

**Issue by brianredbeard** [coreos/matchbox#518]
ItThe [documentation](https://github.com/coreos/matchbox/blame/d4e33efb38b326dafe961ba03c1936f47f36f26a/Documentation/deployment.md#L138) for matchbox refers to the script `cert-gen` used to generate TLS assets.  When searching through the release tarballs, this script seems to be in the location:

```
core@matchbox ~/matchbox-v0.6.0-linux-amd64 $ find * -name cert-gen
scripts/tls/cert-gen
```

While searching through the source repository this script is located at:

```
$ find * -name cert-gen
examples/etc/matchbox/cert-gen
```

This is due to the fact that in the [`release-files`](https://github.com/coreos/matchbox/blob/d4e33efb38b326dafe961ba03c1936f47f36f26a/scripts/release-files#L22) script the location of the path is changed.  It would be ideal if one of the following could occur:

  - standardize the path of where this script lives
  - change the documentation to make it clear if it is referencing a release asset or a source checkout

**Comment by dghubble** [comment]
Yeah, this is especially confusing because in the source repository, `scripts/tls/k8s-certgen` exists too, which is not for matchbox at all.

I'm in favor of docs continuing to refer to the source location `examples/etc/matchbox/cert-gen` and fixing the release script to change the location.

**Comment by dghubble** [comment]
cc @zbwright @alekssaul
