### ISSUE TITLE
More helpful error output on template parse error

### ISSUE THREAD

**Issue by colhom** [coreos/matchbox#530]
matchbox v0.6.0

```
time="2017-05-16T18:32:00Z" level=debug msg="Matched an Ignition or Container Linux Config template" gro
up=chom-test-metal-worker1 labels=map[uuid:a1c94646-579d-42db-be96-dcf856755cfd mac:52:54:00:29:ea:03 os
:installed] profile=tectonic-worker 
time="2017-05-16T18:32:00Z" level=error msg="error parsing template: template: :4: unexpected \"}\" in o
perand" 
```

It would be helpful if the error message gave a line number and perhaps a few lines of template context around where the error occurred.

**Comment by dghubble** [comment]
The Container Linux Config transpiler (package `ct`) is responsible for parsing Container Linux configs and converting them to Ignition - it provides the line number printout.

https://github.com/coreos/matchbox/blob/master/matchbox/http/ignition.go#L92

cc @dgonyeo

**Comment by dgonyeo** [comment]
I need to give the PR some more of my time, but I believe this will enable what you want: https://github.com/coreos/container-linux-config-transpiler/pull/57

**Comment by dghubble** [comment]
Thanks @dgonyeo, I can vendor that update in whenever its ready. Closing as this is tracked by ct.
