### ISSUE TITLE
403 when pulling "quay.io/coreos/kube-addon-manager"

### ISSUE THREAD

**Issue by antoineco** [coreos/matchbox#557]
*Following up on [that thing I reported on Twitter](https://twitter.com/ThatMightBePaul/status/869677136830808064).*

The [`quay.io/repository/coreos/hyperkube`](https://quay.io/repository/coreos/hyperkube) images ship with a Pod definition for `kube-addon-manager` (cf. `/etc/kubernetes/manifests/addon-manager-singlenode.json`). The main container in this definition has:
```json
  "image": "quay.io/coreos/kube-addon-manager-amd64:v6.4-beta.1"
```

Unfortunately this repository is private (unexisting?) so this Pod fails with an `ErrPullImage` error.

**Comment by dghubble** [comment]
This isn't the right place, Matchbox is a service for automating on-premise cluster creation and happens to have Kubernetes examples. Its not involved in hyperkube images or addon-manager. I think you meant to file this issue with https://github.com/coreos/kubernetes (or perhaps https://github.com/kubernetes-incubator/bootkube where those maintainers)?

You might also wish to provide more detail about the issue you're seeing and your setup. This hasn't been observed in self-hosted Kubernetes clusters (ala bootkube) to my knowledge.

**Comment by antoineco** [comment]
Just did what @pgburt asked me to. https://github.com/coreos/kubernetes/tree/coreos-hyperkube-v1.6.4 seems about right indeed, didn't see the branches there, thanks!

**Comment by antoineco** [comment]
ref coreos/kubernetes#140
