### ISSUE TITLE
Issues installing CoreOS to disk using Matchbox

### ISSUE THREAD

**Issue by cygnus8595** [coreos/matchbox#560]
I'm re-posting this from the Google group by request:

I'm trying to get Matchbox up and running to get automated installs of CoreOS working in my environment, and I'm running into two issues that have me lost.

First off, I was able to get the latest version (1353.7.0 as of now) installed, and it boots up, but if I reboot the server, it drops into emergency mode and never boots up. It get stuck on "a start job is running for dev-disk (cut off)" and stays there.

Then I tried to downgrade to 1298.7.0, and when I boot up a new server, I get an error that says "No matching profile" even though I have no selectors at all on my default group.

Thanks in advance if anyone can help me with this!

**Comment by dghubble** [comment]
Ignition will intentionally crash to the emergency shell if something is wrong (to prevent the false conclusion a machine was provisioned correctly). Wait for the emergency shell

```
journalctl --identifier ignition
```

Concerning "no matching profile", if you've manually written groups, ensure that the JSON is correctly formatted (use `jq`). Invalid configs are ignored. Creating groups through the API requires they validate.

**Comment by dghubble** [comment]
Were you able to make progress?

**Comment by cygnus8595** [comment]
Not yet. I've been quite busy with stuff and I'm getting some help from other teammates. I'll keep you posted.

**Comment by dghubble** [comment]
I suspect the first issue is due to the Container Linux config or Ignition being invalid or missing and the later issue is a syntax error in hand-written group config?

You might try the terraform-based [simple install](https://github.com/coreos/matchbox/blob/master/Documentation/getting-started.md) tutorial which uses the API to add configs so machines perform a disk install and set your SSH key (very minimal). Or if you're not a terraform user, checkout https://github.com/coreos/matchbox/tree/master/examples#manual-examples to be sure your profile, group, and container linux config look similar.

**Comment by dghubble** [comment]
Please re-open if you get more details.

**Comment by aledbf** [comment]
@dghubble I see the same error `No matching profile`. From the docs is not clear how Is possible to configure a default group. Any hints?
Thanks

**Comment by dghubble** [comment]
A group without a selector is a "default" group. Have a look through the examples.

https://github.com/coreos/matchbox/blob/master/Documentation/matchbox.md#groups
https://github.com/coreos/matchbox/blob/master/examples/groups/simple-install/install.json
https://github.com/coreos/matchbox/blob/master/examples/groups/etcd3-install/install.json
https://github.com/coreos/matchbox/blob/master/examples/groups/bootkube-install/install.json
https://github.com/coreos/matchbox/blob/master/examples/groups/etcd3/gateway.json

If you're adding groups to `/var/lib/matchbox/groups` by hand, be sure your JSON is valid.

**Comment by mimmus** [comment]
Same problem for me:
`No matching profile`
with this simple defualt group:
`{
  "id": "install",
  "name": "Simple CoreOS Container Linux Install",
  "profile": "vm",
  "metadata": {}
}
`
