### ISSUE TITLE
Execute dynamic steps during provisioning 

### ISSUE THREAD

**Issue by johscheuer** [coreos/matchbox#570]
Hi,

I wanted to ask if it is possible to execute dynamic steps during provisioning I couldn't find any information about it. 

Our Use-Case:

We want to dynamically generate some data when a node is provisioned (e.q. generate a client-certificate). We don't want to generate the data before the provisioning step (e.q. we could use the same certificate for all nodes). Is there a possibility to execute dynamically before provisioning these steps or is such a feature planned?

Thanks!

**Comment by dghubble** [comment]
Neither Matchbox nor Ignition perform certificate generation during disk provisioning. There aren't any plans to add that.

You'd either provide the data upfront as part of a declarative Container Linux config or write a systemd unit which generates the data (or certificate) or pulls it from some location. One of the benefits of simply writing systemd units is that they can do whatever you like already. For example, in one of the old examples, TLS certificates were pulled from a known location when missing https://github.com/coreos/matchbox/blob/7a2764b17b46fb3c223c5acffcd3accd21d32258/examples/ignition/k8s-controller.yaml#L39. but they could be generated on each node as well.

**Comment by johscheuer** [comment]
The certificate generation isn't our main goal  actually this was just a simple example. So what we actually want is that matchbox can fetch some metadata before it passes the ignition-file to a server. 

For example if we have this ignition snippet on matchbox:

```yaml
[Service]
Type=oneshot
ExecStart=/usr/bin/curl -H "X-Vault-Token: {{.token}}" \
                  -X GET \
                  "{{.vault_endpoint}}/v1/secret/foo" -o /etc/test.crt
```

I want that matchbox fetches a new token from vault for each new provisioned machine. With this new token the machine can fetch another token. So if a machine asks for the ignition file the matchbox server would ask would for a token and put it into the rendered ignition file (no generation on the machine itself).

**Comment by dghubble** [comment]
I noticed the certificates were just your example. Matchbox and Ignition won't execute code (e.g. generate certs or tokens) on your behalf, but from your description, it seems you're ok with fetching the content, which is possible. Your options:

1. Ignition can fetch file contents during disk provisioning (on first boot from disk or if kernel arg is set). In your Container Linux config, you can specify a URL within a block. See files -> contents -> remote -> url in the schema. https://coreos.com/os/docs/latest/configuration.html. In your example, write the script with your token and have ExecStart run the script.

2. Write a systemd service which fetches whatever data you like (or execute code and generate). I outlined this option above.

If you're fetching certain cloud provider data, be aware there is a handy builtin service (implemented via a coreos-metadata.service ala. option 2) that writes to a known location. https://coreos.com/os/docs/latest/dynamic-data.html

**Comment by dghubble** [comment]
Any further comment? If not, I'll close this out.

**Comment by johscheuer** [comment]
Oh, sorry I forgot to close this issue. We solved this by a a small workaround. 

Thanks for your help!
