### ISSUE TITLE
examples/terraform: breaks with "Must provide one of 'content' or 'source' on Terraform 0.9.7-0.9.8

### ISSUE THREAD

**Issue by abh** [coreos/matchbox#580]
running "terraform get; terraform plan" from a repository with a terraform.tfvars barely changed from the example tfvars  file I get this error:

```
$ terraform plan
6 error(s) occurred:

* module.cluster.null_resource.copy-secrets[0]: Must provide one of 'content' or 'source'
* module.cluster.null_resource.copy-secrets[1]: Must provide one of 'content' or 'source'
* module.cluster.null_resource.copy-secrets[2]: Must provide one of 'content' or 'source'
...
```

Commenting out the etcd TLS related provisioner definitions in ssh.tf makes the plan proceed.

**Comment by dghubble** [comment]
I noticed this very recently, I bet you're using Terraform 0.9.7 or 0.9.8?

Terraform 0.9.7 https://github.com/hashicorp/terraform/issues/15177 seems to have broken the `template_file` provider. For now, I've rolled back to Terraform 0.9.6 until a Terraform release with a fix is available.

**Comment by abh** [comment]
yeah, 0.9.8. Thanks!

**Comment by dghubble** [comment]
> Commenting out the etcd TLS related provisioner definitions in ssh.tf makes the plan proceed

Nooo, etcd TLS certificates keys will be needed unless you're enabling `experimental_self_hosted_etcd` (which I don't recommend because its experimental and doesn't use TLS at all).

**Comment by dghubble** [comment]
Ah, thanks for confirming. I'll change the title

**Comment by abh** [comment]
yup, it doesn't error out with 0.9.6. Thank you for the super quick follow-up!

**Comment by dghubble** [comment]
Closing this out since not something we can address in this project's examples. Those using terraform should use Terraform 0.9.6 until a release includes https://github.com/hashicorp/terraform/pull/15273

**Comment by pmoust** [comment]
Terraform 0.9.9 includes the above fix.
