### ISSUE TITLE
bootkube-install: cannot move '/home/core/assets' 

### ISSUE THREAD

**Issue by abh** [coreos/matchbox#584]
On re-running "terraform apply" I get this error:

    module.cluster.null_resource.bootkube-start (remote-exec): mv: cannot move '/home/core/assets' to '/opt/bootkube/assets': Directory not empty

Once when I checked the two directories had the same contents, another time they didn't. I'm not sure if in the latter case it was a fatal error because I should have re-installed the system first instead or if it's an error that the destination directory didn't get updated.

**Comment by dghubble** [comment]
Hm. During a successful deployment with `bootkube-install` (terraform-based), the `bootkube-start` step starts the `bootkube.service` on a controller to perform the one-time initial bootstrapping (uses [bootkube](https://github.com/kubernetes-incubator/bootkube), hence the name). When it succeeds, terraform considers the step complete and does not re-run it on subsequent `terraform apply`. Unfortunately, if bootkube.service failed to bootstrap the cluster, something is wrong. Re-running it on an existing cluster won't address the issue (it does not reconcile). Terraform just retries steps which failed last time, which isn't super helpful here.

So two things:

1. Let's find the cause of the Kubernetes bootstrapping failure.

bootkube start failing isn't usually a transient thing. Its usually some misconfiguration:
* Is etcd-member running (if using on-host etcd) `journalctl -f -u etcd-member.service`?
* Is kubelet.service running `systemctl status kubelet.service`?
* Networking/DNS - Images will be pulled from Quay.io to start the control plane. Can you ping and dig external addresses?
* Are there indicative logs in `journalctl -f -u bootkube.service`?
* During bootstrap, try to use `kubectl --kubeconfig=assets/auth/kubeconfig get pods --all-namespaces` to see how far along in the bootstrapping process it gets.
* Do flannel pods successfully start? If not, not subsequent pods will.
* Check which pods are still running. `docker ps`
* Check logs of pods which failed: `docker ps -a; docker log ID`

2. Perhaps we can make this more clear in future.

* Tweak the `mv` to be a NoOp if assets already exist (which would allow moving on the bootkube start)
* Have some way to mark that bootkube.service ran already and failed. Print some message about how re-running is likely not going to help.

**Comment by abh** [comment]
I only had a minute to look at it today. I think the problem was that etcd wasn't running/working.

I'd disabled the experimental in-cluster etcd, so I didn't have an etcd (I think). I realize now I'm not clear if the default is to have one on the host (and that wasn't working).

I'll look again one of the next days (the hardware I work on take about a bazillion years to boot so I make them pxe boot and then look a while later next I have a minute).

**Comment by dghubble** [comment]
Following [bootkube-install](https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install) (terraform-based), by default etcd with run "on-host", meaning each controller node will be an etcd peer and have a systemd unit `etcd-member.service`.

The [terraform.tfvars.example](https://github.com/coreos/matchbox/blob/master/examples/terraform/bootkube-install/terraform.tfvars.example) comments optional variables (default shown as the value), so if you uncomment and edit to `experimental_self_hosted_etcd = "true"`, etcd will be scheduled as a pod on the cluster instead. This bootstrap and pivot is newer and tricky. The team is still working out some bugs and getting TLS to work.

I recommend the on-host etcd setup right now, I use it in my colocation.

**Comment by abh** [comment]
ok, this is without experimental_self_hosted_etcd. I removed the terraform.tfstate file, re-ran plan and apply and re-installed the host:

```
Jun 20 21:39:04 kube1 systemd[1]: Stopped etcd (System Application Container).
Jun 20 21:39:04 kube1 systemd[1]: Starting etcd (System Application Container)...
Jun 20 21:39:05 kube1 rkt[2859]: "210eda28-dee9-4703-a707-45a11f5e1409"
Jun 20 21:39:05 kube1 etcd-wrapper[2888]: ++ id -u etcd
Jun 20 21:39:05 kube1 etcd-wrapper[2888]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https --mount volume=systemd-dir,target=/run/systemd/system --volume systemd-dir,kind=host,source=/run/systemd/system,readOnly=true --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --volume data-dir,kind=host,source=/var/lib/etcd,readOnly=false --volume etc-ssl-certs,kind=host,source=/etc/ssl/etcd,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=data-dir,target=/var/lib/etcd --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/etcd:v3.2.0 --user=232 --
Jun 20 21:39:05 kube1 etcd-wrapper[2888]: run: stat of host path /etc/ssl/etcd: stat /etc/ssl/etcd: no such file or directory
Jun 20 21:39:05 kube1 systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Jun 20 21:39:05 kube1 systemd[1]: Failed to start etcd (System Application Container).
Jun 20 21:39:05 kube1 systemd[1]: etcd-member.service: Unit entered failed state.
Jun 20 21:39:05 kube1 systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Jun 20 21:39:15 kube1 systemd[1]: etcd-member.service: Service hold-off time over, scheduling restart.
Jun 20 21:39:15 kube1 systemd[1]: Stopped etcd (System Application Container).
Jun 20 21:39:15 kube1 systemd[1]: Starting etcd (System Application Container)...
```

**Comment by abh** [comment]
oh, weird -- I removed the state again and re-ran plan and apply and now those files were setup. Progress. Thank you again!

**Comment by dghubble** [comment]
So your Container Linux hosts are provisioned. Then terraform is used to copy the etcd TLS credentials, kubeconfig, and start bootkube.service via SSH. Admittedly its a bit of a hack, but its the lowest common denominator that moves those credentials securely.

https://github.com/coreos/matchbox/blob/master/examples/terraform/modules/bootkube/ssh.tf

**Comment by dghubble** [comment]
For comparison, the non-terraform Kubernetes example has you move these files by hand, which may be more illustrative when doing it the first time. https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md#bootkube

**Comment by dghubble** [comment]
From the last logs you posted, I'd expect `terraform apply` to complain it wasn't able to run the null_resource.copy-secrets task for each node. You could then rerun `terraform apply` since it reconciles until the system has reached the desired state. 

Two more thoughts:

If terraform claimed the copy-secret step succeeded on each node, but the files aren't there, that sounds like a bug we need to track down (I've noticed, terraform considers the step to succeed/fail based on the last command in the set, but thought it was solved).

You mentioned you removed the state and re-ran apply. Just to clarify, that will regenerate all the manifests for the cluster. Normally you'd just re-run `terraform apply`. Deleting state is good if you PXE boot and provision the cluster again to have a fresh start. Maybe that was mentioned earlier and I'm confusing threads, just wanna be sure this isn't related to different generated assets vs old assets on a node already.

**Comment by dghubble** [comment]
Any news?

We've updated to bootkube v0.5.0 since this was filed and both on-host etcd (default) and experimental self-hosted etcd use TLS.

**Comment by dghubble** [comment]
Its been a month. Please re-open or file a new issue if there are problems.
