### ISSUE TITLE
Metadata from profiles ?

### ISSUE THREAD

**Issue by johnmarcou** [coreos/matchbox#593]
Thank you for matchbox.

There is any way to inject metadata in a profile definition, such as for groups, to be used in a template ?

Thank you.

**Comment by dghubble** [comment]
There is not. The intent is that a Profile is a named set of the various configs (iPXE, Container Linux Config, kickstart, etc) and that metadata variables are able to template those configs.

For Terraform clients, templating is done upfront for all or most Matchbox objects so those examples tend to template a profile for every machine. https://github.com/coreos/matchbox/blob/master/examples/terraform/simple-install/profiles.tf#L1.
