### ISSUE TITLE
Invalid TLS credentials: x509: unhandled critical extension

### ISSUE THREAD

**Issue by rbjorklin** [coreos/matchbox#599]
Trying to run match box and I'm met with `Invalid TLS credentials: x509: unhandled critical extension` because our CA is using [Name Constraints](https://tools.ietf.org/html/rfc2459#section-4.2.1.11) and this extension must be `critical` according to the documentation.

**Comment by dghubble** [comment]
Please provide more thorough details and describe change you hope to see.

Example TLS generation scripts and openssl.conf are provided in https://github.com/coreos/matchbox/tree/master/scripts/tls

**Comment by rbjorklin** [comment]
If support for this extension is part of the Go tls package then this issue can be closed if not maybe it's something to consider supporting?

**Comment by dghubble** [comment]
It looks like that extension isn't supported in Go crypto/x509 yet so it will fail to parse. https://github.com/golang/go/issues/15196
