### ISSUE TITLE
IPMI boot/reboot with Terraform ?

### ISSUE THREAD

**Issue by johnmarcou** [coreos/matchbox#600]
Hi all,

I have just a quick question. I am not a Terraform expert, but could it make sense that `terraform apply` actually able to boot or reboot directly the node via IPMI ?

Is this feature planned ?

Thank you.

**Comment by dghubble** [comment]
Its on my roadmap and I have some rough prototypes. It hasn't been approved to prioritize so I'll note that there is genuine interest, thanks.

**Comment by johnmarcou** [comment]
Thanks for your reply. I guess the ipmi bin and feature could be implemented in matchbox, available by the API, and used by the Terraform matchbox module. This could be awesome !

**Comment by trunet** [comment]
+1 interested here...

@johnmarcou This is a feature request not yet implemented, would you mind reopening this issue?

**Comment by johnmarcou** [comment]
For information, I am using this in Terraform:

```
  provisioner "local-exec" {
      command = "ipmitool -I lanplus -H ${var.ipmi_hostname} -U ${var.ipmi_username} -P ${var.ipmi_password} power reset;"
  }
```

**Comment by dghubble** [comment]
One conclusion from the investigation is that a terraform<->IPMI component likely wouldn't be in the scope of Matchbox itself. Often, a Matchbox deployment provides configurationst o machines across sites, but does not have IPMI access to individual machines (behind VPN, separate networks, etc). Instead, an independent proxy might be more appropriate, but this is on hold.

Ultimately, just having terraform run ipmitool like above provides much of the functionality for single-DC setups.
