### ISSUE TITLE
Update Ignition and CT version

### ISSUE THREAD

**Issue by dghubble** [coreos/matchbox#606]
There have been several releases we might pull in.

**Comment by dghubble** [comment]
Perhaps we wait a bit or only update to whatever version of CT had Ignition v0.14.0 https://github.com/coreos/bugs/issues/2063

**Comment by drobakowski** [comment]
An update to at least CT [v0.3.1](https://github.com/coreos/container-linux-config-transpiler/releases/tag/v0.3.1) would be very helpful to fix some bugs like https://github.com/coreos/bugs/issues/1960 / https://github.com/coreos/container-linux-config-transpiler/pull/66.

**Comment by dghubble** [comment]
We'll probably hop directly to a recent CT just to skip over the period where Ignition had several regressions btw v0.15 - v0.17.1.
