### ISSUE TITLE
Fuze update requested

### ISSUE THREAD

**Issue by TerraTech** [coreos/matchbox#621]
CoreOS: 1409.7.0
matchbox: v0.6.1

Can ignition/Fuze (container-linux-config-transpiler) be vendored up to include the following abilities?
https://github.com/coreos/container-linux-config-transpiler/commit/d9eb71c2c77f6269abbc6d15a16fed9b45faddf1#diff-55746646f84e39324ac72516ebd056fd
Including the fix for ```etcd_endpoints```: https://github.com/coreos/container-linux-config-transpiler/commit/873cfedffbf077d3d02330c2b6edb62ca935d92d

I just spent far too long trying to figure out why the following wasn't be respected by the transpiler:
```
locksmith:
  etcd_endpoints: "http://example.com:2379"
```
Even though it is documented that it will:
https://coreos.com/os/docs/1409.7.0/configuration.html

Thanks!

**Comment by dghubble** [comment]
Dup #606
