### ISSUE TITLE
Listen on IPv4 as well as IPv6

### ISSUE THREAD

**Issue by cehoffman** [coreos/matchbox#630]
I'm using the matchbox.service template from contrib and it only comes up listening on IPv6. This prevents talking to the gRPC api from less capable networks.

**matchbox.service**

```
[Unit]
Description=CoreOS matchbox Server
Documentation=https://github.com/coreos/matchbox

[Service]
Environment="IMAGE=quay.io/coreos/matchbox"
Environment="VERSION=v0.6.1"
Environment="MATCHBOX_ADDRESS=0.0.0.0:8080"
Environment="MATCHBOX_RPC_ADDRESS=0.0.0.0:8081"
Environment="MATCHBOX_LOG_LEVEL=debug"
ExecStartPre=/usr/bin/mkdir -p /etc/matchbox
ExecStartPre=/usr/bin/mkdir -p /var/lib/matchbox/assets
ExecStart=/usr/bin/rkt run \
  --net=host \
  --inherit-env \
  --trust-keys-from-https \
  --mount volume=data,target=/var/lib/matchbox \
  --mount volume=config,target=/etc/matchbox \
  --volume data,kind=host,source=/var/lib/matchbox \
  --volume config,kind=host,source=/etc/matchbox \
  ${IMAGE}:${VERSION}
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**ip addr show**

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s20f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether 0c:c4:7a:e5:48:16 brd ff:ff:ff:ff:ff:ff
3: enp0s20f1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master bond0 state DOWN group default qlen 1000
    link/ether 0c:c4:7a:e5:48:17 brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 0c:c4:7a:e5:48:16 brd ff:ff:ff:ff:ff:ff
    inet 147.75.76.9/31 brd 147.75.76.9 scope global bond0
       valid_lft forever preferred_lft forever
    inet 10.99.88.1/31 brd 10.99.88.1 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 2604:1380:4:1e00::1/127 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ec4:7aff:fee5:4816/64 scope link
       valid_lft forever preferred_lft forever
```

**netstat -tlnp**

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::8081                 :::*                    LISTEN      1069/matchbox
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd
tcp6       0      0 :::8080                 :::*                    LISTEN      1069/matchbox
```

I'm fully expecting that I might be doing something wrong related to rkt when launching the matchbox container, but I haven't had much experience with practical IPv6 usage.

**Comment by dghubble** [comment]
I imagine you're following the [Installing on CoreOS](https://coreos.com/matchbox/docs/latest/deployment.html#coreos) docs based on your matchbox.service unit, except with `Environment="MATCHBOX_RPC_ADDRESS=0.0.0.0:8081"` and the log level set directly.

Running the same `matchbox.service` on a CoreOS stable 1409.7.0 box,

```
$ netstat -nltp
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::8081                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::8080                 :::*                    LISTEN      -      
```

But its displayed like that because its listening on IPv4 and IPv6.

```
$ curl 127.0.0.1:8080
matchbox
$ curl -g -6 http://[::1]:8080
matchbox
```

```
$ ss -nlt -6
State       Recv-Q Send-Q       Local Address:Port                      Peer Address:Port              
LISTEN      0      128                     :::8081                                :::*                  
LISTEN      0      128                     :::22                                  :::*                  
LISTEN      0      128                     :::8080                                :::*  
```

I think this stackoverflow [answer](https://unix.stackexchange.com/questions/237731/why-are-ipv4-tcp-connections-showing-as-tcp6) is a nice writeup.

**Comment by cehoffman** [comment]
I'll have to try again. I had a problem reaching the gRPC service from my remote machine. Nothing should have been blocked, but a 2nd look over is warranted. Matchbox not listening on IPv4 seemed unlikely, but was all I had going.

**Comment by dghubble** [comment]
Ok, lemme know if you can't get https://coreos.com/matchbox/docs/latest/deployment.html#verify to succeed.

**Comment by cehoffman** [comment]
Just set it up again and it looks like I had two errors from separate programs that lead me to believe I wasn't reaching the endpoint.

1. Using the terraform matchbox provider I had set the endpoint to `https://matchbox:8081`, this should have been `matchbox:8081`. The error returned was `context deadline exceeded`.

2. When I tried the openssl verify on the matchbox host it worked just fine. When I tried it from my provisioning computer I got `14675:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/ssl/s23_clnt.c:593:`. This upon further inspection is about openssl trying an unsupported TLS/SSL version.

The openssl that comes bundled with macOS Sierra can not connect to the matchbox gRPC endpoint for verification. I tried with the homebrew installed openssl with success, but that version is not installed in a way to override the system version. Someone has to explicitly seek out to use that version.

**Comment by dghubble** [comment]
What version of `terraform-provider-matchbox` are you using? I've made some improvements since the initial release that _should_ show better error messages.

I'm on Linux and not too familiar with the macOS default openssl vs homebrew. Is it the version being old? The server is fairly strict about TLS certificate properties https://github.com/coreos/matchbox/blob/master/matchbox/tlsutil/info.go#L52

**Comment by cehoffman** [comment]
It is 0.2.1 for the terraform provider.


```sh
$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
$ ~/.homebrew/opt/openssl/bin/openssl version
OpenSSL 1.0.2l  25 May 2017
```

I don't think the bundled macOS version has TLS 1.2.

**Comment by dghubble** [comment]
Ok, maybe I add a more explicit check in terraform-provider-matchbox for if someone puts an http or https protocol on the rpc endpoint so its easier to notice.

**Comment by cehoffman** [comment]
Hah, yeah just so used to everything dealing with terraform having an HTTP endpoint that I just typed it without thinking. I was checking the hostname for errors but didn't even think of the scheme for a while. Does gRPC have a scheme? `grpc://`?

**Comment by dghubble** [comment]
`grpc.Dial(target string, opts...)` expects a `host:port` target per their [example client](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L42).
