### ISSUE TITLE
Use map (object) and array on group.metadata

### ISSUE THREAD

**Issue by jcmoraisjr** [coreos/matchbox#634]
I'm using Matchbox with Terraform and need to use maps and arrays on metadata attributes from Terraform's group resource. I can confirm Matchbox supports maps and slices pretty well but cannot say the same about the provider. Any plan to add such data types?

**Comment by dghubble** [comment]
I've written about the issues at https://github.com/coreos/terraform-provider-matchbox/issues/10 (sorry, issues were disabled). Matchbox supports maps and slices in metadata, but the Terraform type system (and provider plugins) doesn't.

**Comment by dghubble** [comment]
Unfortunately, I don't think there is anything matchbox or the matchbox-terraform-provider plugin can do about this unless the HCL types change.

**Comment by jcmoraisjr** [comment]
Thanks for clarifying this and linking the discussion on the provider.
