### ISSUE TITLE
Consider marking get-coreos as an example only

### ISSUE THREAD

**Issue by dghubble** [coreos/matchbox#641]
We currently provide a script `get-coreos` which curls some images and verifies them. Users file pull requests to change it to suit various needs and tastes often. Having that script elevates it to a maintained component that tries to please everyone when its just an example script. I'd like to consider removing it entirely or marking it as a "feature-complete" example. 

Most distros just have users download and verify images on their own. Or they build an official installer tool. No odd scripts in between.

rel. #636 #637 #623 #609 #638 #498 #375 #336 #334 #138

**Comment by enilfodne** [comment]
I respectfully, have to disagree.

It does a crucial job - it fetches assets needed for matchbox to work at all.

As per the listed changes - those changes are often issues that people encounter, i don't want to waste time tweaking / fixing something as simple as fetching assets, when there's a high chance, someone encountered those exact problems - before me.

The script removal would make sense if, based on configuration, matchbox itself, fetches images and/or directs the iPXE bootloader to do so.

**Comment by dghubble** [comment]
Thanks for the feedback, good points. The likely outcome is just that this issue can be referenced when PR's expand the scope of the bash script.

> it fetches assets needed for matchbox to work at all

This isn't true. Tossing images (or anything) in the matchbox `/var/lib/matchbox/assets` is a handy trick to serve them over HTTP, but it is by no means required. Its mainly for use in a pinch if you don't have a file server.

Fun fact: You can provision clusters from the public images and I've tried to highlight that in the Kubernetes example https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install#optional

```
cached_install = "false"
```

If you leave that false, you don't need to download Container Linux images at all. Or clusters can be written to pull from any HTTP caching server. Lots of options.

> It does a crucial job ... those changes are often issues that people encounter

Yes, absolutely. It does serve a useful purpose, which is why it was written originally. I'd just prefer that if we're going to expand it out, we build a proper tool rather than this bash script with many opinion. Or ask folks to use it as a base example. I'll edit the title to not mention removing it though
