### ISSUE TITLE
Profile references in groups require profile's filename to match. 

### ISSUE THREAD

**Issue by mrrandrade** [coreos/matchbox#663]
Issues reference profiles with the directive:

```
  "profile": "issue",
```
Profiles have  an **id** and a **name** fields. But none of them appear to be relevant; what really matters is the profile's filename.

Tests:

```
# cat group/issue.json 
{
  "id": "issuegroup",
  "name": "Coreos Issue group example",
  "profile": "issueprofile",
  "selector": {
    "label": "issue"
  }
}

# cat profile/issue.json
{
  "id": "issueprofile",
  "name": "Coreos Issue profile example",
  "ignition_id": "issue.yaml"
}
```

**Test 1**: correct id, mismatched file name: 
```
# curl "http://matchbox:8080/ignition?label=issue"
Oct 22 05:43:15 matchbox docker[31747]: time="2017-10-22T07:43:15Z" level=info msg="No profile named: issueprofile" group=issuegroup group_name="Coreos Issue group example" labels=map[label:issue]
```
**Test 2**: correct id and matching filename:
```
# mv profiles/issue.json profiles/issueprofile.json
# curl "http://matchbox:8080/ignition?label=issue"
Oct 22 05:45:20 matchbox docker[31747]: time="2017-10-22T07:45:20Z" level=debug msg="Matched an Ignition or Container Linux Config template" group=issuegroup labels=map[label:issue] profile=issueprofile
```

**Test 3**: filename matching the name listed in group profile, but profile itself has irrelevant id/name:
```
# cat profiles/issueprofile.json
{
  "id": "iguessthisshouldntwork",
  "name": "iguessthisshouldntwork",
  "ignition_id": "issue.yaml"
}
# curl "http://matchbox:8080/ignition?label=issue"
Oct 22 05:46:39 matchbox docker[31747]: time="2017-10-22T07:46:39Z" level=debug msg="Matched an Ignition or Container Linux Config template" group=issuegroup labels=map[label:issue] profile=iguessthisshouldntwork
```
I'm not sure if this is expected behaviour.

**Comment by dghubble** [comment]
Yes. The `fileStore` is a simple implementation of the `Store interface` that saves Matchbox object types as files and keys by filename. The `id` field contains the id you'd key by and the `name` is a human readable description to be generalizable to other storage backends (etcd, SQL, datastore, etc.)

* https://github.com/coreos/matchbox/blob/master/matchbox/storage/storagepb/storage.proto#L5

When you use the Matchbox API, the id is indeed used for put's and get's (e.g. issueprofile is written as `issueprofile.json`). I think your question arises when manipulating the representations manually.

**Comment by mrrandrade** [comment]
Yes, it's a couple of hand made examples from my team's lab with matchbox.

I am guessing they were expecting some kind of validation in case the id field do not match the file name, but it's loosely coupled that way. Just thought about reporting since it might save others the debugging headache.

**Comment by dghubble** [comment]
Ok, hope that clear things up.
