### ISSUE TITLE
having issue while running bootkube 

### ISSUE THREAD

**Issue by dpoison** [coreos/matchbox#666]
Hello, 

I am trying to set one controller node and 2 worker node with etcd cluster on both workers. I can set bootstrap with matchbox and ignition and etcd cluster is working fine with 2 worker nodes. But for controller node, it is giving an error. 

Request to help me on this. 
Env Info: 
provisioner.example.com  > 192.168.51.80 > my dhcp, tftp, xientd, dns, matchbox server
controller.example.com > 192.168.51.208 > Should be controller node. 
worker1.example.com > 192.168.51.210 > shoudl be worker node with etcd
worker2.example.com > 192.168.51.211 > shoudl be worker node with etcd
Link folowed is :  [https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md](url)

Here are the steps I am following. 

`root@provisioner $ ./bin/linux/bootkube render --asset-dir=assets --api-servers=https://controller.example.com:8080  --api-server-alt-names=DNS=controller.example.com,IP=192.168.51.208 --etcd-servers=https://worker1.example.com:2379,https://worker2.example.com:2379 --network-provider=experimental-calico`

`root@provisioner $ cp -r /root/matchbox-v0.6.1-linux-amd64/assets/* /var/lib/matchbox/assets/ && chown -R matchbox:matchbox /var/lib/matchbox`

`root@provisioner $ systemctl restart dhcpd xinetd tftp named matchbox && rm -rf /root/.ssh/known_hosts`

Other files in /var/lib/matchbox/ are attached. 
[matchbox.zip](https://github.com/coreos/matchbox/files/1426097/matchbox.zip)

Than switched on 2 worker node and controller node with network boot. 

After rebooting all 3 machines, I found etcd cluster is working fine on both worker node. 
Than tried to start bootkube with following steps. 

`for node in 'controller'; do
    scp -r /var/lib/matchbox/assets/tls/etcd-* /var/lib/matchbox/assets/tls/ca.crt /var/lib/matchbox/assets/tls/etcd core@$node.example.com:/home/core/
    ssh core@$node.example.com 'sudo mkdir -p /etc/ssl/etcd && sudo mv etcd-* etcd /etc/ssl/etcd/ && sudo chown -R etcd:etcd /etc/ssl/etcd && sudo chmod -R 500 /etc/ssl/etcd/'
done`

`for node in 'controller' 'worker1' 'worker2'; do
    scp /var/lib/matchbox/assets/auth/kubeconfig core@$node.example.com:/home/core/kubeconfig
    ssh core@$node.example.com 'sudo mv kubeconfig /etc/kubernetes/kubeconfig'
done`

`scp -r /var/lib/matchbox/assets core@controller.example.com:/home/core/`
`ssh core@controller.example.com 'sudo mkdir -p /opt/bootkube/assets && sudo mv assets/* /opt/bootkube/assets/ && ls -l /opt/bootkube/assets/ && sudo systemctl start bootkube && journalctl -f -u bootkube'`

after many attamtp I am stuck with bellow errors from journalctl

`journalctl -f - u kubelet`
`Oct 30 06:05:16 controller.example.com kubelet-wrapper[3039]: E1030 06:05:16.727072    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get http://controller.example.com:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:16 controller.example.com kubelet-wrapper[3039]: E1030 06:05:16.728056    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get http://controller.example.com:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:16 controller.example.com kubelet-wrapper[3039]: E1030 06:05:16.729175    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get http://controller.example.com:8080/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:17 controller.example.com kubelet-wrapper[3039]: E1030 06:05:17.728382    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get http://controller.example.com:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:17 controller.example.com kubelet-wrapper[3039]: E1030 06:05:17.729115    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get http://controller.example.com:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:17 controller.example.com kubelet-wrapper[3039]: E1030 06:05:17.730609    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get http://controller.example.com:8080/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:18 controller.example.com kubelet-wrapper[3039]: E1030 06:05:18.729745    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get http://controller.example.com:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:18 controller.example.com kubelet-wrapper[3039]: E1030 06:05:18.730881    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get http://controller.example.com:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:18 controller.example.com kubelet-wrapper[3039]: E1030 06:05:18.731790    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get http://controller.example.com:8080/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:19 controller.example.com kubelet-wrapper[3039]: E1030 06:05:19.732037    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get http://controller.example.com:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:19 controller.example.com kubelet-wrapper[3039]: E1030 06:05:19.732038    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get http://controller.example.com:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:19 controller.example.com kubelet-wrapper[3039]: E1030 06:05:19.733092    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get http://controller.example.com:8080/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: I1030 06:05:20.272989    3039 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: I1030 06:05:20.276110    3039 kubelet_node_status.go:82] Attempting to register node controller.example.com
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: E1030 06:05:20.277016    3039 kubelet_node_status.go:106] Unable to register node "controller.example.com" with API server: Post http://controller.example.com:8080/api/v1/nodes: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: W1030 06:05:20.485947    3039 status_manager.go:431] Failed to get status for pod "bootstrap-kube-apiserver-controller.example.com_kube-system(73e8d9c1cc2eb2d868efdcacf69e42df)": Get http://controller.example.com:8080/api/v1/namespaces/kube-system/pods/bootstrap-kube-apiserver-controller.example.com: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: W1030 06:05:20.486881    3039 status_manager.go:431] Failed to get status for pod "bootstrap-kube-controller-manager-controller.example.com_kube-system(507e3b02a6381193c6e29576c559a686)": Get http://controller.example.com:8080/api/v1/namespaces/kube-system/pods/bootstrap-kube-controller-manager-controller.example.com: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: W1030 06:05:20.487693    3039 status_manager.go:431] Failed to get status for pod "bootstrap-kube-scheduler-controller.example.com_kube-system(95dac44d414b7e4fcee3f0edc2df871b)": Get http://controller.example.com:8080/api/v1/namespaces/kube-system/pods/bootstrap-kube-scheduler-controller.example.com: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: E1030 06:05:20.733410    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get http://controller.example.com:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: E1030 06:05:20.734096    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get http://controller.example.com:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:20 controller.example.com kubelet-wrapper[3039]: E1030 06:05:20.735238    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get http://controller.example.com:8080/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:21 controller.example.com kubelet-wrapper[3039]: W1030 06:05:21.678091    3039 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 30 06:05:21 controller.example.com kubelet-wrapper[3039]: E1030 06:05:21.678226    3039 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Oct 30 06:05:21 controller.example.com kubelet-wrapper[3039]: E1030 06:05:21.735893    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get http://controller.example.com:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:21 controller.example.com kubelet-wrapper[3039]: E1030 06:05:21.735902    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get http://controller.example.com:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused
Oct 30 06:05:21 controller.example.com kubelet-wrapper[3039]: E1030 06:05:21.736832    3039 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get http://controller.example.com:8080/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller.example.com&resourceVersion=0: dial tcp 192.168.51.208:8080: getsockopt: connection refused`

**Comment by dghubble** [comment]
> one controller node and 2 worker node with etcd cluster on both workers

The examples setup etcd peers across controller nodes, not worker nodes. Fix `--etcd-servers` to correspond to the controller.

**Comment by dpoison** [comment]
> I'm skeptical. The workers aren't configured to be peers, don't know about each other, and lack the TLS credentials to be setup properly. You might be checking something else by accident. I expect systemctl status etcd-member won't show a running etcd.

Well manual installation it is done ( 1 controller and 2 worker, and 2 etcd cluster on 2 worker node)

I am trying this same with bootkube. Via bootkube able to create 2 etcd cluster on 2 worker node. But while setting up a controller, its not able to register controller or worker. 

> The examples setup etcd peers across controller nodes, not worker nodes. Fix --etcd-servers to correspond to the controller.

--etcd-servers is already given in kube-apiserver.yaml file. 

**You can check files I have uploaded**

**Comment by dghubble** [comment]
The Kubernetes example runs etcd peers across controllers and works correctly. Matchbox can be used to provision Container Linux machines however you like (Kubernetes, Mesos, custom services, standalone-etcd, anything) but beyond the provided examples, designing/debugging clusters is a user responsibility.

In your particular custom case (not for other readers!),
* Be sure workers are configured with an etcd-member dropin https://github.com/coreos/matchbox/blob/master/examples/ignition/bootkube-controller.yaml#L7
* Be sure you move bootkube generated etcd TLS credentials to nodes where etcd runs.
* Be sure the etcd cluster is healthy. Use `systemctl status etcd-member` or `etcdctl cluster-health` with the appropriate flags to TLS files
* Your Kubernetes cluster should have one backing etcd cluster, not two.
* Your kubelet logs aren't useful. The error you see over and over is consistent with any cluster that hasn't bootstrapped successfully, likely due to your etcd changes. Check `bootkube` logs. Use `kubectl get pods` if bootstrapping occurs. Gather logs. This is part of customizing clusters that diverge from the provided examples.

More broadly:
* https://www.freedesktop.org/software/systemd/man/systemd.service.html
* https://coreos.com/os/docs/latest/configuration.html

Aside: that matchbox.zip isn't a zipfile. 

I'm closing this because this isn't an issue with Matchbox and the examples are correct.
