### ISSUE TITLE
systemd.units.`enabled` is not seen in /ignition JSON

### ISSUE THREAD

**Issue by redbaron** [coreos/matchbox#668]
Using matchbox 0.6.1, it seems that `enabled` is not working when fetching JSON from /ignition. Changing it back to 'enable' works fine.

If I create following in ignition profile yaml:

```
systemd:
  units:
    - name: test.service
      enabled: true
      contents: |
        [Unit]
        Description=true
        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=/bin/true
        [Install]
        WantedBy=multi-user.target
```

then there is no field `enabled` when fetching JSON `/ignition` endpoint:

```
curl -s 'http://192.168.121.156:8080/ignition?uuid=9d087fdf-f8a5-44f6-8ca7-a6ad9b44bbf8&mac=52-54-00-f7-78-09' | jq '.systemd.units|map(select(.name=="test.service"))[0]'
{
  "name": "test.service",
  "contents": "[Unit]\nDescription=true\n[Service]\nType=oneshot\nRemainAfterExit=true\nExecStart=/bin/true\n[Install]\nWantedBy=multi-user.target\n"
}
```

should I change it to `enable`, it then appears:
```
{
  "name": "test.service",
  "enable": true,
  "contents": "[Unit]\nDescription=true\n[Service]\nType=oneshot\nRemainAfterExit=true\nExecStart=/bin/true\n[Install]\nWantedBy=multi-user.target\n"
}
```

Reason I tried to change it  from `enable` to `enabled`, is following warning in ignition output:
```
Nov 03 12:03:37 localhost ignition[369]: files: the enable field has been deprecated in favor of enabled
```
,but it seems that it can't be done with current version of matchbox

**Comment by dghubble** [comment]
The `enable` to `enabled` switch is part of the Ignition v2.0.0 to v2.1.0 switch. You'll see the deprecation warning on newer Container Linux machines because Matchbox vendors [container-linux-config-transpiler](https://github.com/coreos/container-linux-config-transpiler) v0.4.2 and serves Ignition v2.0.0 configs.

The next Matchbox release will update the version, but this does drop support for Container Linux versions before the switch.

**Comment by redbaron** [comment]
this means that in current version unknown field `enabled` is silently ignored, rather than returning an error, is it intentional?

**Comment by crawford** [comment]
@redbaron Yes, Ignition will _warn_ you about unknown fields, but it won't error out. This is more of a limitation of Go's JSON parsing libraries than anything.
