### ISSUE TITLE
json and yaml? External config via url?

### ISSUE THREAD

**Issue by mleklund** [coreos/matchbox#679]
More questions then true issues.  As a newcomer the mix of yaml and json for configuration is a bit weird. Ignition makes a point of using yaml because it handles newlines and is more readable. What is the logic behind the profiles and groups being json? Is that because that’s what terraform outputs? Also has any thought been put into groups, profiles, and ignition being pulled from external systems via url includes?

**Comment by dghubble** [comment]
> Ignition makes a point of using yaml because

Ignition is written in JSON format and intended for consumption by machines. https://coreos.com/ignition/docs/latest/configuration-v2_1.html

Those writing configs for Container Linux instances (admins, etc.) should prefer [Container Linux Configs](https://coreos.com/os/docs/latest/configuration.html), a YAML format that is converted to Ignition by tools like `ct` (CLI) or Matchbox (which also allows templating). Its much friendlier to read and write [examples](https://github.com/coreos/matchbox/tree/master/examples/ignition) - the directory has to be called `ignition` for backwards compatibility, I apologize for the confusion.

> What is the logic behind the profiles and groups being json?

Matchbox uses a storage interface, with Group and Profile data types. The default implementation is a filestore, located at `/var/lib/matchbox` which represents each object in a JSON schema. Consider it an internal detail. If you were to write a storage implementation for Postgres or etcd the on-disk format would be different.

> Is that because that’s what terraform outputs?

No, no relation to Terraform. You don't have to use Terraform to use Matchbox either. Matchbox has a general gRPC API for which clients can be generated in a variety of languages that support protobuf/gRPC.

> ignition being pulled from external systems via url includes?

Ignition (and by extension Container Linux Configs) allow including remote contents. See `append` and `replace` in the spec linked above. The feature isn't used in any Matchbox cluster examples.
