### ISSUE TITLE
Bootloop using tectonic baremetal installer

### ISSUE THREAD

**Issue by MartijnStraatman** [coreos/matchbox#684]
Hello,
After a succesfull first boot ( installer service ran fine), a bootloop occurs. The pxe booted instance keeps pxe booting and fails with a gpt table error and reboots again. 

We are running pxe booted images on Openstack (Openstack installer is not supported) with dnsmasq and matchbox. Any suggestions?

**Comment by MartijnStraatman** [comment]
We did a succesfull installation with the same setup. Only difference is the terraform installer instead of the tectonic gui installer

**Comment by dghubble** [comment]
If you're having an issue with Tectonic, please file issues on Tectonic Installer. Tectonic on Openstack isn't supported in any capacity that I'm aware of.

Boot loops usually mean your boot order isn't set according to the Tectonic requirements. https://coreos.com/tectonic/docs/latest/install/bare-metal/requirements.html
