### ISSUE TITLE
terraform bootkube example missing ssh-agent step

### ISSUE THREAD

**Issue by mleklund** [coreos/matchbox#685]
If you are following the examples the secrets never get copied and the cluster never starts.  It may be obvious to most, but was not to me, and I only came across it by reading through the typhoon documentation here: https://typhoon.psdn.io/bare-metal/#ssh-agent

**Comment by dghubble** [comment]
Yes, it would be good to include the same warning note here. Users of terraform need to be aware it will use your ssh-agent, which needs to be properly setup.
