### ISSUE TITLE
docs/bootkube: ssh-keys example hyperlink to 404

### ISSUE THREAD

**Issue by AlexxNica** [coreos/matchbox#688]
The 2nd step from `https://github.com/coreos/matchbox/blob/v0.7.0/Documentation/bootkube.md#assets` (`Add your SSH public key to each machine group definition *as shown*.`) hyperlinks to a `404: Page Not Found` due to a typo.

Current hyperlink URL: `https://coreos.com/matchbox/docs/v0.7.0/README.html#ssh-keys`
Correct hyperlink URL: `https://coreos.com/matchbox/docs/0.7.0/README.html#ssh-keys`

**Comment by dghubble** [comment]
cc @zbwright

**Comment by zbwright** [comment]
Sorry for the delay. I completely missed this ticket. Issue appears to be fixed. Thanks for calling it out, @AlexxNica

**Comment by dghubble** [comment]
The source link seems to be correct, versions begin with a "v". https://github.com/coreos/matchbox/blob/v0.7.0/examples/README.md#ssh-keys

It seems the docs site doesn't use the "v"?

**Comment by dghubble** [comment]
cc @crawford @chancez I hear you two are familiar with the docs syncing system?

**Comment by dghubble** [comment]
Looks like relative links like ` [profile](../examples/profiles)` get converted to a `v0.7.0` reference?

**Comment by zbwright** [comment]
also, please note that within the repo, the links work correctly. it's the rendered site page that is incorrectly linking to versioned html, rather than 'latest', but only for two links.

**Comment by crawford** [comment]
It seems odd to me that we are linking to the README from the documentation.

Regardless, re-syncing using the latest version of `sync` fixes the issue. It also fixed a number of other broken links.

**Comment by dghubble** [comment]
Thanks!
