### ISSUE TITLE
Spinning VM in mac

### ISSUE THREAD

**Issue by krishdey** [coreos/matchbox#702]
As demonstrated here https://www.youtube.com/watch?time_continue=43&v=61tSi50rfRI
How am i suppose to spin up the VM in MAC laptop ?
Moreover couldn't find boot-tectonic scripts as shown in the video.

A pointer to do will be really appreciated.

Thanks

**Comment by dghubble** [comment]
Matchbox examples cover Linux only, launch containers natively, and launch QEMU/KVM VMs. You'll probably need to ask @philips to share any macOS scripts used.

Tectonic is a separate project from Matchbox. You can find Tectonic docs in https://coreos.com/tectonic/docs/latest/install/bare-metal/
