### ISSUE TITLE
render v2.2.0 Ignition configs

### ISSUE THREAD

**Issue by TerraTech** [coreos/matchbox#715]
We need to have access to:
ignition : security : tls : certificateAuthorities

Which was added to the v2.2.0 ignition config spec that is now marked stable.

This is so that we are able to use self-signed certificates as we can't find a way for ignition to allow for them.
e.g. _curl --insecure_ or _wget --no-check-certificate_

I see matchbox-0.7.0 just implemented v2.1.0.  Can you provide how far out on the roadmap when v2.2.0 will be supported?

Thanks!

**Comment by rockwyc992** [comment]
I found that ignition config spec v2.3.0 is stable, too. [link](https://github.com/coreos/ignition/releases/tag/v0.29.0)

However, matchbox support this feature, render ignition, by  Container Linux config transpiler. Maybe we just need to bump our vender only?

**Comment by rockwyc992** [comment]
like what #670 do.

**Comment by dghubble** [comment]
See #740

**Comment by naphta** [comment]
is there any reason why the upgrade didn't go to v2.3.0? that appears to be the latest version shipped with stable coreos
