### ISSUE TITLE
matchbox desktop environment: making the battery panel work

### ISSUE THREAD

**Issue by estellnb** [coreos/matchbox#744]
I have installed the matchbox battery panel on my EEEPC 4G but it fails to display the battery status though upower can display the battery state correctly and though sysfs can do so as well:

cat /sys/class/power_supply/BAT0/status
upower -i /org/freedesktop/UPower/devices/battery_BAT0
... both work

The sysfs path needs to be updated in mb-applet-battery.c:
https://git.yoctoproject.org/cgit/cgit.cgi/matchbox-panel/tree/applets/mb-applet-battery.c
#define ACPI_PREFIX	"/proc/acpi"
#define BAT_PREFIX	"battery/BAT0"
#define AC_PREFIX	"ac_adapter/AC0"
<SNIP>
f = fopen(ACPI_PREFIX "/" BAT_PREFIX "/info", "r");

**Comment by estellnb** [comment]
However I fear that things are not as easy as to replace /proc/ACPI/... with /sys/class/... as I have just noticed that the reference is BAT1 instead of BAT0 on another notebook of me:
> cat /sys/class/power_supply/BAT1/status
Full / Discharging
> cat /sys/class/power_supply/BAT1/capacity
96 ... means 96% charged
> cat /sys/class/power_supply/ADP1/online
1 ... if ac adapter is plugged
0 ... if ac adapter is unplugged

**Comment by lucab** [comment]
@estellnb I think you hit the wrong bug tracker. To report bugs for the Yocto project, see https://wiki.yoctoproject.org/wiki/Bug_reporting_and_Information_levels.

**Comment by estellnb** [comment]
I am not sure on how to report an error for "errors.yoctoproject.org/Errors/". The interface only seems to support bug querying; no login; no filing of new bugs. Or do you know the email of a matchbox developer I could turn to?

**Comment by dghubble** [comment]
I think you must be referring to a different Matchbox project and this is indeed not the project you're looking for
